### ISSUE TITLE
todays_events.ex:34 crash on nil 'today' ref

### ISSUE THREAD

**Issue by ekarak** [drizzle-org/drizzle#10]
```
Initializing todays events

10:41:42.300 [error] GenServer #PID<0.682.0> terminating
** (stop) exited in: GenServer.call(Drizzle.TodaysEvents, {:update, #Function<7.53584698/1 in Drizzle.TodaysEvents.update/1>}, 5000)
    ** (EXIT) an exception was raised:
        ** (Protocol.UndefinedError) protocol Enumerable not implemented for nil of type Atom. This protocol is implemented for the following type(s): CubDB.Btree, CubDB.Btree.Diff, CubDB.Btree.KeyRange, Range, File.Stream, Map, Date.Range, IO.Stream, GenEvent.Stream, MapSet, List, HashSet, HashDict, Function, Stream
            (elixir 1.10.3) lib/enum.ex:1: Enumerable.impl_for!/1
            (elixir 1.10.3) lib/enum.ex:141: Enumerable.reduce/3
            (elixir 1.10.3) lib/enum.ex:3383: Enum.reverse/1
            (elixir 1.10.3) lib/enum.ex:1180: Enum.group_by/3
            (drizzle 0.1.1) lib/drizzle/todays_events.ex:34: Drizzle.TodaysEvents.calculate_start_stop_time/1
```

**Comment by ekarak** [comment]
this is related to the recent change in the schedule storage: 
(scheduler.ex, line 48)
```
  defp execute_scheduled_events do
    if current_time() == 0 || TodaysEvents.current_state() == [] do
      TodaysEvents.reset()

      current_day_of_week()
      |> Schedule.get()
      |> TodaysEvents.update()
    end
```
Schedule.get() returns nil, it should at least return an empty struct.

**Comment by ekarak** [comment]
there are numerous issues here, I tried setting default to empty map `Schedule.get(%{})` but:
```
12:55:31.673 [error] GenServer #PID<0.650.0> terminating
** (stop) exited in: GenServer.call(:fri, {:read, {:get, %{}, nil}, 5000}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.10.3) lib/gen_server.ex:1013: GenServer.call/3
    (drizzle 0.1.1) lib/drizzle/scheduler.ex:53: Drizzle.Scheduler.execute_scheduled_events/0
    (drizzle 0.1.1) lib/drizzle/scheduler.ex:21: Drizzle.Scheduler.handle_info/2
    (stdlib 3.12.1) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib 3.12.1) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :work
State: %{}
``` 
1) today is Saturday 
2)

**Comment by ekarak** [comment]
In retro, I think I'll rewrite the scheduler logic
